# Generated by Django 3.2.5 on 2021-07-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Bprice', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('Sprice', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('offer', models.CharField(choices=[('True', 'True'), ('False', 'False')], default=False, max_length=30)),
                ('image', models.ImageField(upload_to='products/images')),
                ('amount', models.DecimalField(decimal_places=2, default='1', max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.subcategory')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
