# Generated by Django 3.2.5 on 2021-07-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_menuentries_submenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='menuentries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='product.menuentries'),
        ),
    ]
