# Generated by Django 3.2.5 on 2021-07-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_menuentries_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
