# Generated by Django 3.2.5 on 2021-07-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdatetime', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('beat', models.CharField(max_length=255)),
                ('grid', models.CharField(max_length=255)),
                ('crimedescr', models.CharField(max_length=255)),
                ('ucr_ncic_code', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
